#=================================================
# https://github.com/zhiern/OpenWRT
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: 🪨 Rockchip

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
    # - cron: 0 17 * * *
  # watch:
  #   types: started

env:
  REPO_URL: https://github.com/openwrt/openwrt
  IMM_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: configs/rockchip.config
  DIY_SCRIPT: scripts/diy-rockchip.sh
  CLASH_KERNEL: arm64
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: Rockchip
  
jobs:
  build:
    runs-on: ubuntu-24.04

    steps: 
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        
    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Install Caddy Server
      run: |
        sudo curl -sL -o /usr/bin/caddy https://github.com/zhiern/ZeroWrt-Action/releases/download/Caddy/caddy
        sudo chmod 755 /usr/bin/caddy
        echo ":8080 {" > caddyfile
        echo "    root * $(pwd)" >> caddyfile
        echo "    file_server browse" >> caddyfile
        echo "}" >> caddyfile
        sudo /usr/bin/caddy start --config caddyfile --adapter caddyfile
        
    - name: Free disk space
      uses: zhiern/actions@free-disk

    - name: Checkout
      uses: actions/checkout@main

    - name: Build System Setup
      uses: zhiern/actions@openwrt-build-setup

    - name: Install LLVM
      uses: zhiern/actions@install-llvm
                
    - name: Clone Source Code
      run: |
        df -hT $GITHUB_WORKSPACE
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        git clone $IMM_URL -b $REPO_BRANCH immortalwrt
        cd openwrt
        rm -rf ./target/linux/rockchip
        cp -rf ../immortalwrt/target/linux/rockchip ./target/linux/rockchip
        curl -o feeds.conf.default https://raw.githubusercontent.com/zhiern/ZeroWrt-Action/refs/heads/openwrt-24.10/Customize/feeds/feeds.conf.default
        rm -rf package/boot/{rkbin,uboot-rockchip,arm-trusted-firmware-rockchip}
        cp -rf ../immortalwrt/package/boot/uboot-rockchip ./package/boot/uboot-rockchip
        cp -rf ../immortalwrt/package/boot/arm-trusted-firmware-rockchip ./package/boot/arm-trusted-firmware-rockchip
        sed -i '/REQUIRE_IMAGE_METADATA/d' target/linux/rockchip/armv8/base-files/lib/upgrade/platform.sh
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        COMMIT_AUTHOR=$(git show -s --date=short --format="作者: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        COMMIT_DATE=$(git show -s --date=short --format="时间: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git show -s --date=short --format="内容: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "CURRENT_DATE=$(date +%s)" >> $GITHUB_ENV
        
    - name: Generate Variables
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig > /dev/null 2>&1
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV

    - name: Cache Toolchain
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}
        
    - name: Install Feeds
      run: |
        cd $OPENWRT_PATH
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Load Custom Configuration
      run: |
        export GITEA_USERTNAME=${{ secrets.GITEA_USERTNAME }}
        export GITEA_PASSWORD=${{ secrets.GITEA_PASSWORD }}
        [ -e files ] && mv files $OPENWRT_PATH/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
        chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        chmod +x $DIY_SCRIPT
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/$DIY_SCRIPT
        $GITHUB_WORKSPACE/scripts/preset-mihimo-core.sh $CLASH_KERNEL
        $GITHUB_WORKSPACE/scripts/preset-adguard-core.sh $CLASH_KERNEL
        
    - name: Download DL Package
      run: |
        cd $OPENWRT_PATH
        make defconfig
        make download -j8
        
    - name: Compile Firmware
      id: compile
      run: |
        cd $OPENWRT_PATH
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
        
    - name: Check Space Usage
      if: (!cancelled())
      run: df -hT
        
    - name: Upload Bin Directory
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: Online Rockchip updates
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH
        mkdir -p ota
        OTA_URL="https://github.com/zhiern/ZeroWrt-Action/releases/download"
        SHA256_armsom_sige3=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-armsom_sige3-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_armsom_sige7=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-armsom_sige7-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_t4=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopc-t4-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_t6=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopc-t6-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r2c_plus=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r2c-plus-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r2c=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r2c-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r2s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r3s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r3s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r4s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r4se=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r4se-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r5c=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r5c-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r5s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r5s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r6c=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r6c-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r6s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-friendlyarm_nanopi-r6s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_huake_guangmiao_g4c=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-huake_guangmiao-g4c-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r66s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-lunzn_fastrhino-r66s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_r68s=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-lunzn_fastrhino-r68s-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_radxa_rock_5a=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-radxa_rock-5a-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_radxa_rock_5b=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-radxa_rock-5b-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_xunlong_orangepi_5_plus=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-xunlong_orangepi-5-plus-squashfs-sysupgrade.img.gz | awk '{print $1}')
        SHA256_xunlong_orangepi_5=$(sha256sum bin/targets/rockchip/armv8*/openwrt-rockchip-armv8-xunlong_orangepi-5-squashfs-sysupgrade.img.gz | awk '{print $1}')
        cat > ota/ota.json <<EOF
        {
          "armsom,sige3": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "SHA256_armsom_sige3",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-armsom_sige3-squashfs-sysupgrade.img.gz"
            }
          ],
          "armsom,sige7": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_armsom_sige7",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-armsom_sige7-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopc-t4": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_t4",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopc-t4-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopc-t6": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_t6",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopc-t6-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r2c-plus": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r2c_plus",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r2c-plus-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r2c": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r2c",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r2c-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r2s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r2s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r3s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r3s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r3s-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r4s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r4s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r4se": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r4se",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r4se-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r5c": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r5c",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r5c-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r5s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r5s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r5s-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r6c": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r6c",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r6c-squashfs-sysupgrade.img.gz"
            }
          ],
          "friendlyarm,nanopi-r6s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r6s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-friendlyarm_nanopi-r6s-squashfs-sysupgrade.img.gz"
            }
          ],
          "huake,guangmiao-g4c": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_huake_guangmiao_g4c",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-huake_guangmiao-g4c-squashfs-sysupgrade.img.gz"
            }
          ],  
          "lunzn,fastrhino-r66s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r66s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-lunzn_fastrhino-r66s-squashfs-sysupgrade.img.gz"
            }
          ],
          "lunzn,fastrhino-r68s": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_r68s",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-lunzn_fastrhino-r68s-squashfs-sysupgrade.img.gz"
            }
          ],
          "radxa,rock-5a": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_radxa_rock_5a",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-radxa_rock-5a-squashfs-sysupgrade.img.gz"
            }
          ],
          "radxa,rock-5b": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_radxa_rock_5b",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-radxa_rock-5b-squashfs-sysupgrade.img.gz"
            }
          ],
          "xunlong,orangepi-5-plus": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_xunlong_orangepi_5_plus",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-xunlong_orangepi-5-plus-squashfs-sysupgrade.img.gz"
            }
          ],
          "xunlong,orangepi-5": [
            {
              "build_date": "$CURRENT_DATE",
              "sha256sum": "$SHA256_xunlong_orangepi_5",
              "url": "$OTA_URL/Rockchip/openwrt-rockchip-armv8-xunlong_orangepi-5-squashfs-sysupgrade.img.gz"
            }
          ]
        }
        EOF
        
    - name: Organize Files
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        mv -f $OPENWRT_PATH/ota/* ./
        cat sha256sums
        cp $OPENWRT_PATH/.config build.config
        mkdir -p kernel
        mv -f packages/* kernel
        tar -zcf kernel.tar.gz kernel
        rm -rf packages feeds.buildinfo version.buildinfo kernel
        echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        
    - name: Upload Firmware To Artifact
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-firmware-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: Upload Firmware To Release
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ env.FIRMWARE_TAG }}
        allowUpdates: true
        tag: ${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is OpenWrt Firmware**
          ### 📒 固件信息
          - 💻 平台架构: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          - ⚽ 固件源码: ${{ env.REPO_URL }}
          - 💝 源码分支: ${{ env.REPO_BRANCH }}
          - 🚀 内核版本: ${{ env.KERNEL }}
          - 🌐 默认地址: 10.0.0.1
          - 🔑 默认密码: password
          ### 🧊 固件版本
          - 固件编译前最后一次➦[主源码](${{ env.REPO_URL }})更新记录
          - ${{ env.COMMIT_AUTHOR }}
          - ${{ env.COMMIT_DATE }}
          - ${{ env.COMMIT_MESSAGE }}
          - ${{ env.COMMIT_HASH }}
